export const UI_TEXT = {
  interceptorLogTitle: "Interceptor Log",
  interceptorLogSubtitle: "Real-time API call trace",
  interceptorLogEmpty: "Waiting for API calls...",
  clearButtonLabel: "Clear",
  realApiCallsTitle: "Real API Calls (JSONPlaceholder)",
  realApiCallsDescription: "These hit a real external API — all responses pass through the same interceptor",
  fireRequestButton: "Fire Request",
  fetchingButton: "Fetching...",
  allErrorsClearedMessage: "All errors dismissed. API monitor is clear.",
  activeErrorsTitle: "Active Errors",
  dismissAllButtonLabel: "Dismiss all",
  totalLabel: "Total",
  successLabel: "Success",
  failedLabel: "Failed",
  appTitle: "API Monitor",
  appSubtitle: "LearningBox · AppPageFirst",
  appDescription: "All API calls pass through the common interceptor. Failed calls are caught and displayed below.",
  appIcon: "📡",
};
