/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface LbCalendar {
        /**
          * Pass events as JSON string: '[{"day":3,"title":"...","type":"...","dot":"#hex"}]'
          * @default ''
         */
        "events": string;
        /**
          * Highlight today's date
          * @default true
         */
        "highlightToday": boolean;
    }
}
export interface LbCalendarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLLbCalendarElement;
}
declare global {
    interface HTMLLbCalendarElementEventMap {
        "dateSelected": string;
    }
    interface HTMLLbCalendarElement extends Components.LbCalendar, HTMLStencilElement {
        addEventListener<K extends keyof HTMLLbCalendarElementEventMap>(type: K, listener: (this: HTMLLbCalendarElement, ev: LbCalendarCustomEvent<HTMLLbCalendarElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLLbCalendarElementEventMap>(type: K, listener: (this: HTMLLbCalendarElement, ev: LbCalendarCustomEvent<HTMLLbCalendarElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLLbCalendarElement: {
        prototype: HTMLLbCalendarElement;
        new (): HTMLLbCalendarElement;
    };
    interface HTMLElementTagNameMap {
        "lb-calendar": HTMLLbCalendarElement;
    }
}
declare namespace LocalJSX {
    interface LbCalendar {
        /**
          * Pass events as JSON string: '[{"day":3,"title":"...","type":"...","dot":"#hex"}]'
          * @default ''
         */
        "events"?: string;
        /**
          * Highlight today's date
          * @default true
         */
        "highlightToday"?: boolean;
        /**
          * Fires when a date is selected, detail = ISO date string
         */
        "onDateSelected"?: (event: LbCalendarCustomEvent<string>) => void;
    }

    interface LbCalendarAttributes {
        "events": string;
        "highlightToday": boolean;
    }

    interface IntrinsicElements {
        "lb-calendar": Omit<LbCalendar, keyof LbCalendarAttributes> & { [K in keyof LbCalendar & keyof LbCalendarAttributes]?: LbCalendar[K] } & { [K in keyof LbCalendar & keyof LbCalendarAttributes as `attr:${K}`]?: LbCalendarAttributes[K] } & { [K in keyof LbCalendar & keyof LbCalendarAttributes as `prop:${K}`]?: LbCalendar[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "lb-calendar": LocalJSX.IntrinsicElements["lb-calendar"] & JSXBase.HTMLAttributes<HTMLLbCalendarElement>;
        }
    }
}
